### ISSUE TITLE
any plans to release to maven?

### ISSUE THREAD

**Issue by austin-sandia** [intel/daal#30]
that could really spur usage among java devs . . . the binary download is not so easy to add to a standard java project . . .

**Comment by dr-pain** [comment]
It is in our future plans.

**Comment by almson** [comment]
Releasing to maven is crucial.

The worst part about the `daal.jar` that is bundled now is that **it doesn't have javadoc.** This necessitates workarounds.

Please also include `libJavaApi.so` in the jar. You can look at `JCuda`, `com.github.fommil.netlib`, or `JavaCPP` for examples how this can be done.

At the least, add a `pom.xml` to the source code so that it is easy to build and install locally.

**Comment by dr-pain** [comment]
Hello almson!

> Please also include libJavaApi.so in the jar. You can look at JCuda, com.github.fommil.netlib, or JavaCPP for examples how this can be done.
we can`t simple include libJavaApi.so into jar because: this isn`t single so which daal jar depend of; daal support 6 platforms (lnx/mac/win + 32bit/64bit), so all binaries somehow needs to be included into jar to continue support of these platforms.
instead of including all kind of binaries into jar, we plan to have 5 separate zip packages. daal users will be needed to download-unpack binaries thru maven-dependency-plugin. exact zip file may be choosed via profiles.

> At the least, add a pom.xml to the source code so that it is easy to build and install locally.
I have attached pom.xml to this post. Could you look at it and tell us your opinion 
about chosen scheme of daal at maven publishing?

[pom.zip](https://github.com/intel/daal/files/1978831/pom.zip)
Andrey

**Comment by almson** [comment]
Did you look at JCuda or Netlib before coming up with your own method of handling the native libraries? Because your method sucks.

**Comment by dr-pain** [comment]
Hello almson!

thank you for pointing us to jcuda. I have looked at at their implementation and  it looks really better than my proposal (from customers point of view). I need to finish some experiments, but looks like we will use the same approach in DAAL.

Andrey

PS: I considered packaging DAAL binaries into jar (instead of zip), but missed some key details.

**Comment by dr-pain** [comment]
Hello almson!

We have published DAAL at maven central today. Repository address is  http://central.maven.org/maven2/com/intel/daal.
To use DAAL in maven projects just add following dependency into .pom file:
    <dependency>
      <groupId>com.intel.daal</groupId>
      <artifactId>daal</artifactId>
      <version>2019.0.001</version>
    </dependency>

Andrey
