### ISSUE TITLE
Files in daal-daal_2018_update1.zip are corrupt

### ISSUE THREAD

**Issue by MSchusterDcb** [intel/daal#43]
I downloaded the zip archive for the 2018_update1 and the files in ".\externals\mklfpk\win\lib" seem to be corrupt. The lib files just have a size of 1 kb and seem to contain build information. However, the files in the repo seem to be ok.

**Comment by VasiliyR** [comment]
Hi,

This archives were created automatically by GitHub during release creation and seem like it was not able to proceed correctly files which are belong Git LFS(we have enable this solution for storing large binary files starting this release). We will escalate this problem to GitHub support team, but for now due to we are not able to repack source archives I can propose to you only to clone repository using Git client, please note what you must have enabled Git LFS module in your client.

Please let me know have any another questions or I can close this issue.

WBR,
Vasily
