### ISSUE TITLE
libdaal_core Archive File Not Downloaded Properly

### ISSUE THREAD

**Issue by Kadle11** [intel/daal#47]
The File: daal/externals/mklfpk/lnx/lib/intel64/libdaal_vmlipp_core.a is supposed to be an Archive of a size of about 19.5 MB when seen on GitHub, But when the command:  git clone --recursive https://github.com/01org/daal.git, Specified on the DAAL Page is run, The File that is retrieved is a Text file of size 133 Bytes with the Following contents:

version https://git-lfs.github.com/spec/v1
oid sha256:e8f293258e38e9689cb87ffbb91c3de2c339a6c074c77115ca86d50b5a48bc64
size 20413048

How to access the right Archive File?

**Comment by VasiliyR** [comment]
Hi Kadle11,

Due to you've closed this issue I believe what you already figure out how to solve of this issue... but just in case if not: you need to install "Git Large File Storage (LFS) extension" (https://git-lfs.github.com/) as noted in "Required Software" section to be able to clone binary files correctly.

WBR,
Vasily

**Comment by Kadle11** [comment]
Thank you Vasily, 
Yes, I did the same.
